In [ ]:
!pip install numpy


In [1]:
import numpy as np
#create arrays using numpy
ar1=np.array([1,2,3,4,5,6])
print(ar1)
print(type(ar1))
#type of array
print(ar1.shape)
#in single dimension only one number is avialable 
#one d array have only one braces
re=ar1.reshape(1,6)#1row 6 coloum
print(re)


[1 2 3 4 5 6]
<class 'numpy.ndarray'>
(6,)
[[1 2 3 4 5 6]]


In [ ]:
#2d array
arr=np.array([[1,2,3,4,5,6],[1,2,3,4,5,6]])
arr.shape#2rows and 6 coloum


(2, 6)

In [ ]:
#create array using inbuilt function
#arange fuunction is used to iterate from 0-10 eith ++2
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [15]:
#ones function is used to create the 2d array with all ones in it 
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [20]:
#identity matrix digonal element is ones 
#2d matrix of m=n
np.eye((3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
arr=np.array([[1,2,3,4,5],[1,2,3,4,5]])
print(arr)
print(arr.shape)
print(arr.ndim)#used to find dimension
print(arr.dtype)#find data type
print(arr.itemsize)#how much bytes is used
print(arr.size)#no of elements

[[1 2 3 4 5]
 [1 2 3 4 5]]
(2, 5)
2
int64
8
10


In [ ]:
##vector numpy operation 
###return type a;so be an array 
arr1=np.array([1,23,4,5,6])
arr2=np.array([1,2,3,4,5])
#element wise addition 
print("addition is ", arr1+arr2)
#elme,emt wise subtraction 
print("subtraction is ", arr1-arr2)
print("addition is ", arr1*arr2)

addition is  [ 2 25  7  9 11]
addition is  [ 0 21  1  1  1]
addition is  [ 1 46 12 20 30]


In [29]:
arr=np.array([2,3,4,5,6])
print(np.sqrt(arr))
print(np.exp(arr))
print(np.sin(arr))
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [40]:
#array slicing and indexing 
arr=np.array([[1,2,3,4,5],[2,3,4,5,6],[1,2,3,4,5]])
print("\n",arr)
print(arr[0][0])
print(arr[1:])#it iterate over 1row to nth row
print(arr[1: ,2:])#it iterate rom 1 row to nth an in row
#from 2 coloum to nth coloum
print(arr[0:2,3:])




 [[1 2 3 4 5]
 [2 3 4 5 6]
 [1 2 3 4 5]]
1
[[2 3 4 5 6]
 [1 2 3 4 5]]
[[4 5 6]
 [3 4 5]]
[[4 5]
 [5 6]]


In [ ]:
#modify array element 
arr[0][0]=100
print(arr)
arr[1:2]=[100,200,300,200,500]
print(arr)

[[100   2   3   4   5]
 [100 200 300 200 500]
 [100 100 100 100 100]]
[[100   2   3   4   5]
 [100 200 300 200 500]
 [100 100 100 100 100]]


In [49]:
#statical concept normalization
data=np.array([1,2,3,4,5])
print(np.mean(data))
print(np.std(data))
print(np.median(data))
print(np.var(data))
#normalization
normalizeddata=(data-np.mean(data))/np.std(data)
print(normalizeddata)


3.0
1.4142135623730951
3.0
2.0
[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [60]:
#logical operation 
arr=np.array([1,2,3,4,5,8,9,10,2003])
print(data[(data>2)|(data<10)])


[1 2 3 4 5]
